name: Build & Push Docker to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node + pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run lint check
      - name: Run Linter
        run: pnpm run lint

      # Run Next.js build check
      - name: Run Build
        run: pnpm run build

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build, tag, and push Docker image
      - name: Build, Tag, Push image
        run: |
          IMAGE_REPO_NAME=portfolio
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_URI=$ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG

          echo "🚀 Building image $ECR_URI"
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

          echo "🔖 Tagging image"
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_URI

          echo "📤 Pushing image"
          docker push $ECR_URI

          echo "✅ Image pushed: $ECR_URI"
